// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mQC1XMXYWXGKmfAIhGGiA5PmRi2xNPc',
    appId: '1:1075892564973:web:16edb5efdaf469c96cede4',
    messagingSenderId: '1075892564973',
    projectId: 'ecopunto-ucn',
    authDomain: 'ecopunto-ucn.firebaseapp.com',
    storageBucket: 'ecopunto-ucn.firebasestorage.app',
    measurementId: 'G-Z4B2XS7CT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7c0O_u85dHFY_h2lwcOcNUvaaL6sJDE',
    appId: '1:1075892564973:android:044aa6b799b9b9466cede4',
    messagingSenderId: '1075892564973',
    projectId: 'ecopunto-ucn',
    storageBucket: 'ecopunto-ucn.firebasestorage.app',
  );
}
